### ISSUE TITLE
Replicating the Swiss roll dataset

### ISSUE THREAD

**Issue by prrao87** [Topology-and-Data/manifold-learning#3]
I'm trying to produce the Swiss roll dataset using the equations specified in the source Python notebook, but I'm having no luck. 

```julia
function make_swiss_roll(n)
    """
    Continuous swiss-roll shaped manifold
    """
    t = range(0, 1, length = n)
    u = t
    v = @. 3π / 2 * (0.1 + 2t)
    # Swiss roll transformation
    x = @. -v * cos(v)'
    y = u'
    z = @. v * sin(v)'
    return x, y, z
end
```
![image](https://user-images.githubusercontent.com/35005448/115073998-1866c180-9ec7-11eb-9c0c-784007698801.png)

Once again, it seems like a dimensionality-related issue.

It makes sense to look at the [existing implementation in `ManifoldLearning.jl`](https://github.com/wildart/ManifoldLearning.jl/blob/af839e3e9862298148b09695790046904b9c7f54/src/utils.jl#L63) and understanding how they did it.

**Comment by prrao87** [comment]
I was able to produce the plotu, but I'm not able to explain how/why it works.

```julia
function make_swiss_roll(n = 100)
    """
    Continuous swiss-roll shaped manifold
    """
    t = range(0, 1, length = n)
    u = @. 3π / 2 * (0.1 + 2t)'
    # Swiss roll transformation
    x = [-v * cos(v) for v in u]
    y = @. ones(n)' * t
    z = [v * sin(v) for v in u]
    return x, y, z
end

x, y, z = make_swiss_roll(100)
plot(
    x, y, z, seriestype = :surface, legend = false,
)
```
![image](https://user-images.githubusercontent.com/35005448/115300298-ca072c00-a12d-11eb-8249-621710d5d49e.png)

```julia
>>> println(size(x), size(y), size(z))
>>> (1, 50)(50, 50)(1, 50)
```
x and z are both Matrices of size `1 x n`, and y is a matrix of size `n x n`. Why does it have to be specified this way?

**Comment by jha-vikas** [comment]
function make_swiss_roll_kron(n = 10, R_max=2)
           T = range(0,1,length=n)
           R = @. 0.1 + R_max * T
           x = kron((@. R * cos(-3*3.14*T)), ones(n))
           y = kron((@. R * sin(-3*3.14*T)), ones(n))
           z = kron(ones(n),T)
           return x,y,z
       end

This is something I figured. The direction of the roll is opposite to what you have, but that is trivial matter. However, I am not able to plot in 3-d. 2-d plot between x,y give a spiral and extruding it in z should give the swiss roll. Can you see if you can plot it?
Error I am getting is:

 ***   IDENTICAL DATA POINTS.
   NDP =  100   IP1 =    1   IP2 =    2   XD=0.1   YD=-0
 ERROR DETECTED IN ROUTINE   IDTANG.

**Comment by prrao87** [comment]
@jha-vikas you're getting that error because you aren't using the PyPlot backend. By default, `Plots.jl` loads the GR backend. Install PyPlot (`add PyPlot` in the package manager) and then call it as the backend during import:

```julia
using Plots
pyplot()
```

That'll at least allow you to begin making 3D plots (the GR backend isn't very good at supporting 3D plots). 

The other problem you have is that the types of your output from the Kronecker function are all 1D arrays (vectors).

```julia
x, y, z = make_swiss_roll_kron(50)

>>> println(typeof(x), typeof(y), typeof(z))
Vector{Float64}Vector{Float64}Vector{Float64}
```

To make a 3D plot, you can't have all three coordinates as 1D arrays - at least one of them has to be a 2D array (matrix) so that you have a "meshgrid" equivalent. Try reshaping them accordingly and seeing if the extrusion works.

**Comment by prrao87** [comment]
I think we learned what we could from this exercise. Closing.
